---
- name: Configure AAP
  hosts: localhost
  vars_files:
    - vars/config-as-code/controller/credentials.yml
    - vars/config-as-code/controller/execution_environments.yml
    - vars/config-as-code/controller/inventories.yml
    - vars/config-as-code/controller/inventory_sources.yml
    - vars/config-as-code/controller/job_templates.yml
    - vars/config-as-code/controller/organizations.yml
    - vars/config-as-code/controller/projects.yml
    - vars/config-as-code/controller/schedules.yml
    - vars/config-as-code/controller/settings.yml
    - vars/config-as-code/controller/users.yml
    - vars/config-as-code/controller/workflow_templates.yml

  roles:
    - redhat_cop.controller_configuration.dispatch
